CREATE TABLE pais(
id_pais INTEGER GENERATED BY DEFAULT AS IDENTITY,
nome_pais VARCHAR2 (30)
);

ALTER TABLE pais ADD PRIMARY KEY(id_pais);

CREATE TABLE estado(
id_estado INTEGER GENERATED BY DEFAULT AS IDENTITY,
nome_estado VARCHAR2 (30),
id_pais INTEGER
);

ALTER TABLE estado ADD PRIMARY KEY(id_estado);

ALTER TABLE estado ADD CONSTRAINT fk_estado FOREIGN KEY (id_pais) REFERENCES pais (id_pais);

CREATE TABLE cidade(
id_cidade INTEGER GENERATED BY DEFAULT AS IDENTITY,
nome_cidade VARCHAR2 (30),
id_estado INTEGER
);

ALTER TABLE cidade ADD PRIMARY KEY(id_cidade);

ALTER TABLE cidade ADD CONSTRAINT fk_cidade FOREIGN KEY (id_estado) REFERENCES estado (id_estado);

CREATE TABLE bairro(
id_bairro INTEGER GENERATED BY DEFAULT AS IDENTITY,
nome_bairro VARCHAR2 (30),
id_cidade INTEGER
);

ALTER TABLE bairro ADD PRIMARY KEY(id_bairro);

ALTER TABLE bairro ADD CONSTRAINT fk_bairro FOREIGN KEY (id_cidade) REFERENCES cidade (id_cidade);

CREATE TABLE endereco_cliente(
id_endereco INTEGER GENERATED BY DEFAULT AS IDENTITY,
cep NUMBER,
logradouro VARCHAR2(50),
numero number,
referencia VARCHAR2(50),
id_bairro INTEGER
);

ALTER TABLE endereco_cliente ADD PRIMARY KEY(id_endereco);

ALTER TABLE endereco_cliente ADD CONSTRAINT fk_endereco FOREIGN KEY (id_bairro) REFERENCES bairro (id_bairro);
